<a href="https://colab.research.google.com/github/sumukhsuresh2003/Understanding-Machine-Learning-Algorithms-PESU-IO-Slot-14/blob/main/EDA.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [ ]:
dataset = pd.read_csv('cancer patient data sets.csv')

In [ ]:
x = dataset.iloc[:,:-1].values
y = dataset.iloc[:,-1].values

In [ ]:
dataset.shape

(1000, 24)

In [ ]:
dataset.describe()

Age       Gender  Air Pollution  Alcohol use  Dust Allergy  \
count  1000.000000  1000.000000      1000.0000  1000.000000   1000.000000   
mean     37.174000     1.402000         3.8400     4.563000      5.165000   
std      12.005493     0.490547         2.0304     2.620477      1.980833   
min      14.000000     1.000000         1.0000     1.000000      1.000000   
25%      27.750000     1.000000         2.0000     2.000000      4.000000   
50%      36.000000     1.000000         3.0000     5.000000      6.000000   
75%      45.000000     2.000000         6.0000     7.000000      7.000000   
max      73.000000     2.000000         8.0000     8.000000      8.000000   

       OccuPational Hazards  Genetic Risk  chronic Lung Disease  \
count           1000.000000   1000.000000           1000.000000   
mean               4.840000      4.580000              4.380000   
std                2.107805      2.126999              1.848518   
min                1.000000      1.000000              1.000000   
25%                3.000000      2.000000              3.000000   
50%                5.000000      5.000000              4.000000   
75%                7.000000      7.000000              6.000000   
max                8.000000      7.000000              7.000000   

       Balanced Diet      Obesity  ...  Coughing of Blood      Fatigue  \
count    1000.000000  1000.000000  ...        1000.000000  1000.000000   
mean        4.491000     4.465000  ...           4.859000     3.856000   
std         2.135528     2.124921  ...           2.427965     2.244616   
min         1.000000     1.000000  ...           1.000000     1.000000   
25%         2.000000     3.000000  ...           3.000000     2.000000   
50%         4.000000     4.000000  ...           4.000000     3.000000   
75%         7.000000     7.000000  ...           7.000000     5.000000   
max         7.000000     7.000000  ...           9.000000     9.000000   

       Weight Loss  Shortness of Breath     Wheezing  Swallowing Difficulty  \
count  1000.000000          1000.000000  1000.000000            1000.000000   
mean      3.855000             4.240000     3.777000               3.746000   
std       2.206546             2.285087     2.041921               2.270383   
min       1.000000             1.000000     1.000000               1.000000   
25%       2.000000             2.000000     2.000000               2.000000   
50%       3.000000             4.000000     4.000000               4.000000   
75%       6.000000             6.000000     5.000000               5.000000   
max       8.000000             9.000000     8.000000               8.000000   

       Clubbing of Finger Nails  Frequent Cold    Dry Cough      Snoring  
count               1000.000000    1000.000000  1000.000000  1000.000000  
mean                   3.923000       3.536000     3.853000     2.926000  
std                    2.388048       1.832502     2.039007     1.474686  
min                    1.000000       1.000000     1.000000     1.000000  
25%                    2.000000       2.000000     2.000000     2.000000  
50%                    4.000000       3.000000     4.000000     3.000000  
75%                    5.000000       5.000000     6.000000     4.000000  
max                    9.000000       7.000000     7.000000     7.000000  

[8 rows x 23 columns]

In [ ]:
print(x)

[[33  1  2 ...  2  3  4]
 [17  1  3 ...  1  7  2]
 [35  1  4 ...  6  7  2]
 ...
 [25  2  4 ...  6  7  2]
 [18  2  6 ...  4  2  3]
 [47  1  6 ...  6  7  2]]


In [ ]:
print(y)

['Low' 'Medium' 'High' 'High' 'High' 'High' 'Low' 'Low' 'Medium' 'Medium'
 'High' 'High' 'Medium' 'High' 'Low' 'Medium' 'Medium' 'High' 'High'
 'Medium' 'High' 'High' 'High' 'High' 'High' 'Medium' 'Medium' 'Medium'
 'High' 'Medium' 'High' 'High' 'Medium' 'Low' 'Low' 'Medium' 'Low' 'Low'
 'Low' 'Low' 'Low' 'Low' 'Low' 'Low' 'Low' 'Low' 'High' 'Low' 'Low' 'Low'
 'Low' 'Low' 'Low' 'Low' 'Low' 'Low' 'Low' 'High' 'Low' 'Low' 'Low' 'Low'
 'Low' 'Medium' 'Medium' 'Medium' 'Medium' 'Medium' 'High' 'Medium'
 'Medium' 'Medium' 'Medium' 'Medium' 'Medium' 'Medium' 'Medium' 'Medium'
 'Medium' 'High' 'Medium' 'Medium' 'Medium' 'Medium' 'Medium' 'Medium'
 'Medium' 'High' 'High' 'High' 'Medium' 'High' 'High' 'High' 'High' 'High'
 'High' 'High' 'High' 'High' 'High' 'Medium' 'High' 'High' 'High' 'High'
 'High' 'High' 'High' 'High' 'High' 'High' 'Low' 'Medium' 'High' 'High'
 'High' 'Low' 'Low' 'Medium' 'Medium' 'High' 'High' 'Medium' 'High' 'Low'
 'Medium' 'Medium' 'High' 'High' 'Medium' 'High' 'High' 'H

In [ ]:
dataset.isnull().sum()

Age                         0
Gender                      0
Air Pollution               0
Alcohol use                 0
Dust Allergy                0
OccuPational Hazards        0
Genetic Risk                0
chronic Lung Disease        0
Balanced Diet               0
Obesity                     0
Smoking                     0
Passive Smoker              0
Chest Pain                  0
Coughing of Blood           0
Fatigue                     0
Weight Loss                 0
Shortness of Breath         0
Wheezing                    0
Swallowing Difficulty       0
Clubbing of Finger Nails    0
Frequent Cold               0
Dry Cough                   0
Snoring                     0
Level                       0
dtype: int64

In [ ]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[0])],remainder = 'passthrough' )
x = np.array(ct.fit_transform(x))
print(x)

[[0. 0. 0. ... 2. 3. 4.]
 [0. 1. 0. ... 1. 7. 2.]
 [0. 0. 0. ... 6. 7. 2.]
 ...
 [0. 0. 0. ... 6. 7. 2.]
 [0. 0. 1. ... 4. 2. 3.]
 [0. 0. 0. ... 6. 7. 2.]]


In [ ]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
y=le.fit_transform(y)
print(y)

[1 2 0 0 0 0 1 1 2 2 0 0 2 0 1 2 2 0 0 2 0 0 0 0 0 2 2 2 0 2 0 0 2 1 1 2 1
 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 2 2 2 2 2 0 2 2 2 2 2
 2 2 2 2 2 0 2 2 2 2 2 2 2 0 0 0 2 0 0 0 0 0 0 0 0 0 0 2 0 0 0 0 0 0 0 0 0
 0 1 2 0 0 0 1 1 2 2 0 0 2 0 1 2 2 0 0 2 0 0 0 0 2 2 2 2 0 2 0 0 2 1 1 0 1
 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 2 1 1 1 1 1 2 2 2 2 2 1 2 2 2 2 2
 2 2 2 2 2 1 2 2 2 2 2 2 2 0 0 0 1 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0
 0 2 1 0 0 0 1 1 2 2 0 0 2 1 1 2 2 0 0 2 0 0 0 0 1 2 2 2 0 2 0 0 2 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 1 2 2 2 2 2
 2 2 2 2 2 1 2 2 2 2 2 2 2 0 0 0 1 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0
 0 2 1 0 0 0 1 1 2 2 0 0 2 1 1 2 2 0 0 2 0 0 0 0 1 2 2 2 0 2 0 0 2 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 1 2 2 2 2 2
 2 2 2 2 2 1 2 2 2 2 2 2 2 0 0 0 1 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0
 0 0 1 0 0 0 1 1 2 2 0 0 2 1 1 2 2 0 0 2 0 0 0 0 1 2 2 2 0 2 0 0 2 1 1 2 1
 1 1 1 1 1 1 1 1 1 2 1 1 

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(x,y, test_size = 0.2,random_state =1 )

In [ ]:
print(X_train)

[[0. 0. 0. ... 5. 1. 1.]
 [0. 0. 0. ... 7. 6. 2.]
 [0. 0. 0. ... 2. 3. 1.]
 ...
 [0. 0. 0. ... 1. 7. 6.]
 [0. 0. 0. ... 2. 3. 1.]
 [0. 0. 0. ... 1. 2. 1.]]


In [ ]:
print(X_test)

[[0. 0. 0. ... 4. 2. 5.]
 [0. 0. 0. ... 2. 3. 4.]
 [0. 0. 0. ... 2. 4. 1.]
 ...
 [0. 0. 0. ... 7. 6. 2.]
 [0. 0. 0. ... 1. 2. 2.]
 [0. 0. 0. ... 7. 6. 2.]]


In [ ]:
print(y_train)

[1 0 0 1 2 2 2 1 1 2 2 2 1 0 0 2 0 2 0 1 0 0 1 2 1 0 0 2 0 2 0 0 1 0 1 1 1
 1 2 2 1 2 0 0 1 1 0 0 2 2 2 1 1 0 0 2 0 0 0 1 0 1 2 2 0 1 2 0 0 0 2 0 1 2
 2 0 0 1 0 1 2 0 2 0 2 1 0 0 0 0 2 2 2 2 0 2 2 1 1 2 2 1 2 2 2 0 1 0 0 0 1
 0 1 1 2 2 2 0 1 2 1 1 2 1 1 1 1 2 2 2 1 2 0 2 2 2 0 1 1 1 1 2 0 2 0 2 0 0
 0 2 0 0 0 1 2 0 1 0 2 0 1 2 1 0 0 1 0 2 0 0 0 1 0 1 1 1 2 1 1 0 1 1 0 1 1
 1 1 2 1 0 0 1 0 0 1 1 0 0 0 1 1 1 0 2 2 1 1 0 0 0 1 1 1 2 1 0 1 2 0 2 0 2
 1 0 0 0 2 0 1 1 0 2 0 1 2 1 0 2 0 1 0 1 2 1 2 2 0 1 0 0 0 2 2 2 0 1 1 2 1
 2 2 1 1 1 2 1 1 1 0 1 0 0 0 0 1 0 1 1 2 2 2 1 2 0 0 0 1 1 2 0 0 0 0 1 1 1
 2 2 2 0 2 1 2 1 2 0 2 0 2 0 2 0 1 0 0 2 0 2 0 1 1 0 2 1 2 0 0 0 0 0 2 0 1
 0 2 2 2 1 2 1 0 1 2 2 1 1 1 0 2 0 2 2 2 2 2 0 0 2 0 1 0 2 1 1 0 1 1 0 0 0
 1 0 0 0 0 2 0 1 2 0 2 2 0 0 0 0 0 2 2 0 2 0 0 2 0 0 2 2 1 2 0 0 2 2 0 0 0
 0 2 0 1 0 1 1 0 2 2 0 0 0 2 2 2 2 2 2 1 0 2 1 2 2 2 2 1 0 0 2 1 1 2 2 2 2
 0 2 2 0 2 1 2 0 1 1 2 0 2 1 0 1 2 0 0 2 1 0 0 1 0 2 2 2 2 0 1 0 0 0 1 2 0
 1 2 0 2 2 1 2 1 2 2 1 2 

In [ ]:
print(y_test)

[2 1 2 1 0 1 1 1 0 1 1 0 2 2 2 0 0 1 1 1 1 0 1 1 0 2 0 0 1 1 0 1 2 1 2 1 2
 1 0 1 0 2 2 2 0 0 0 1 2 0 1 1 2 2 1 0 0 0 1 2 2 2 1 0 1 0 0 1 2 0 1 1 2 2
 1 2 2 1 0 2 1 2 0 0 2 0 2 2 0 2 0 2 2 0 2 0 0 1 1 1 1 0 0 1 0 1 1 0 1 1 2
 2 1 1 0 2 1 0 2 0 2 0 0 2 0 0 0 2 2 2 0 2 0 0 0 2 0 2 2 0 2 1 1 0 0 2 2 0
 0 0 0 2 2 2 1 0 1 0 2 1 1 0 1 0 0 2 0 1 0 2 0 2 1 0 0 1 2 2 1 0 0 1 1 1 0
 0 0 2 2 2 1 1 0 2 2 0 0 0 1 0]


In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train[:, 1:] = sc.fit_transform(X_train[:,1:])
X_test[:,1:] = sc.transform(X_test[:1,1:])

In [ ]:
print(X_train)

[[ 0.         -0.14285714 -0.12340351 ...  0.78882614 -1.4272944
  -1.29412598]
 [ 0.         -0.14285714 -0.12340351 ...  1.87874136  1.05387796
  -0.60940324]
 [ 0.         -0.14285714 -0.12340351 ... -0.84604669 -0.43482546
  -1.29412598]
 ...
 [ 0.         -0.14285714 -0.12340351 ... -1.3910043   1.55011243
   2.12948773]
 [ 0.         -0.14285714 -0.12340351 ... -0.84604669 -0.43482546
  -1.29412598]
 [ 0.         -0.14285714 -0.12340351 ... -1.3910043  -0.93105993
  -1.29412598]]


In [ ]:
print(X_test)

[[ 0.         -0.14285714 -0.12340351 ...  4.          2.
   5.        ]
 [ 0.         -0.14285714 -0.12340351 ...  4.          2.
   5.        ]
 [ 0.         -0.14285714 -0.12340351 ...  4.          2.
   5.        ]
 ...
 [ 0.         -0.14285714 -0.12340351 ...  4.          2.
   5.        ]
 [ 0.         -0.14285714 -0.12340351 ...  4.          2.
   5.        ]
 [ 0.         -0.14285714 -0.12340351 ...  4.          2.
   5.        ]]
